# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_100M_0/top_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_100M_0 || ORIG_REF_NAME==top_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/top/ip/top_ps7_0_axi_periph_1/top_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ps7_0_axi_periph_1 || ORIG_REF_NAME==top_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# IP: bd/top/ip/top_qubit_processor_fixed_0_1/top_qubit_processor_fixed_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_qubit_processor_fixed_0_1 || ORIG_REF_NAME==top_qubit_processor_fixed_0_1} -quiet] -quiet

# XDC: /home/soulbird/hls_prac/qc/vivado/qubit_operations/qubit_operations.gen/sources_1/bd/top/top_ooc.xdc
