# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/soulbird/hls_prac/qc/vivado/qubit_operations/qubit_operations.srcs/sources_1/bd/top/ip/top_qubit_processor_fixed_0_1/top_qubit_processor_fixed_0_1.xci
# IP: The module: 'top_qubit_processor_fixed_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/soulbird/hls_prac/qc/vivado/qubit_operations/qubit_operations.gen/sources_1/bd/top/ip/top_qubit_processor_fixed_0_1/constraints/qubit_processor_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_qubit_processor_fixed_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/soulbird/hls_prac/qc/vivado/qubit_operations/qubit_operations.srcs/sources_1/bd/top/ip/top_qubit_processor_fixed_0_1/top_qubit_processor_fixed_0_1.xci
# IP: The module: 'top_qubit_processor_fixed_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/soulbird/hls_prac/qc/vivado/qubit_operations/qubit_operations.gen/sources_1/bd/top/ip/top_qubit_processor_fixed_0_1/constraints/qubit_processor_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_qubit_processor_fixed_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
